// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfFn38Jj_v9u4p12IFgWqo5U5Qj1K2fyc',
    appId: '1:1035980061651:web:24b9782160cba2b6874d26',
    messagingSenderId: '1035980061651',
    projectId: 'todo-flutter-407112',
    authDomain: 'todo-flutter-407112.firebaseapp.com',
    storageBucket: 'todo-flutter-407112.appspot.com',
    measurementId: 'G-BK7S60Y64X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqM1D3GdP9MBdGbuPOpTDWo-6W6P1AxTY',
    appId: '1:1035980061651:android:ab374c0a2ebaf94a874d26',
    messagingSenderId: '1035980061651',
    projectId: 'todo-flutter-407112',
    storageBucket: 'todo-flutter-407112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXKce3JN3UBfMUj4HecBBA6wIxko8lZDg',
    appId: '1:1035980061651:ios:316cf19181102212874d26',
    messagingSenderId: '1035980061651',
    projectId: 'todo-flutter-407112',
    storageBucket: 'todo-flutter-407112.appspot.com',
    androidClientId: '1035980061651-611v6enil2m5mah5v6mfo1rrq42ceev9.apps.googleusercontent.com',
    iosClientId: '1035980061651-csr2o5m0ulpkqm8aaip6um7uuqvo39ca.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXKce3JN3UBfMUj4HecBBA6wIxko8lZDg',
    appId: '1:1035980061651:ios:58dfe4c8303fd692874d26',
    messagingSenderId: '1035980061651',
    projectId: 'todo-flutter-407112',
    storageBucket: 'todo-flutter-407112.appspot.com',
    androidClientId: '1035980061651-611v6enil2m5mah5v6mfo1rrq42ceev9.apps.googleusercontent.com',
    iosClientId: '1035980061651-efc5bled3lnlvuibh5fgvjcugm4qgr61.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
